const WhatIsDeepfake = () => (
  <section className="py-16 px-6 bg-white text-center">
    <h2 className="text-3xl font-bold mb-6">What is a Deepfake?</h2>
    <p className="max-w-3xl mx-auto text-gray-700 text-lg leading-7">
      A deepfake is synthetic media generated by AI to make someone appear to say or do something they never did.
      It's created using deep learning techniques like Generative Adversarial Networks (GANs) and has grown alarmingly realistic — blurring the line between real and fake.
    </p>
  </section>
);

export default WhatIsDeepfake;
